Cmune.Channels.Instrumentation/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cmune.Channels.Instrumentation.Models.Enums;
using Cmune.Channels.Instrumentation.Utils;
using Cmune.Channels.Instrumentation.Business;
using UberStrike.DataCenter.Business;
using UberStrike.DataCenter.Common.Entities;
using Cmune.DataCenter.Common.Utils;
using Cmune.DataCenter.Business;
using UberStrike.DataCenter.Utils;
using UberStrike.Core.Types;

namespace Cmune.Channels.Instrumentation.Controllers
{
    [Authorize(Roles = MembershipRoles.Administrator)]
    public class MapController : BaseController
    {
        public MapController()
            : base()
        {
            ViewBag.Title = ViewBag.ActiveTab = CmuneMenu.MainTabs.Management;
            ViewBag.SubActiveTab = CmuneMenu.ManagementSubTabs.MapItem;
        }

        public ActionResult MapItem()
        {
            ViewBag.ApplicationVersions = MapService.GetMapApplicationVersions();
            return View();
        }

        [HttpPost]
        public PartialViewResult GetMapItems(string applicationVersion)
        {
            MapClusterView mapsCluster = Games.GetMapCluster(applicationVersion);

            ViewBag.ItemCache = new ItemCache(UberStrikeCommonConfig.ApplicationId, true);
            ViewBag.ApplicationVersion = applicationVersion;
            return PartialView("Partial/GetMapItems", mapsCluster);
        }

        public PartialViewResult LoadEditMapItem(string applicationVersion, int mapId)
        {
            var mapView = Games.GetMapView(applicationVersion, mapId);

            ViewBag.ItemCache = new ItemCache(UberStrikeCommonConfig.ApplicationId, true);
            ViewBag.RecommendableItems = CmuneItem.GetRecommendableItemsForMaps(UberStrikeCommonConfig.ApplicationId);
            ViewBag.ApplicationVersion = applicationVersion;
            return PartialView("Partial/MapItemForm", mapView);
        }

        public JsonResult SaveMapItem(string applicationVersion, int mapId, int recommendedItemId)
        {
            bool success = false;
            string message = string.Empty;

            var map = Games.GetMapView(applicationVersion, mapId);
            // TODO should go into business logic
            var recommendedItems = CmuneItem.GetRecommendableItemsForMaps(UberStrikeCommonConfig.ApplicationId);

            if (recommendedItems.Contains(recommendedItemId))
            {
                map.RecommendedItemId = recommendedItemId;
                var operationResult = Games.UpdateMapRecommendedItem(applicationVersion, mapId, recommendedItemId);
                if (operationResult != MapOperationResult.Ok)
                {
                    message = "Error in db occured";
                }
                else
                {
                    success = true;
                    message = "Successfully updated";
                }
                UberStrikeCacheInvalidation.InvalidateOtherCache(BuildType, "UberStrikeMapItemRecommendation");

            }
            else
            {
                message = "Recommended Item not found";
            }

            return new JsonResult { Data = new { success = success, message = message } };
        }


    }
}

Cmune.Channels.Instrumentation/Views/Map/Partial/GetMapItems.cshtml
@model MapClusterView
@{    
    string appVersion = String.Empty;

    if (Model != null)
    {
        appVersion = Model.ApplicationVersion;
    }
}
<form method="post" action="">
<table class="searchResultTable">
    <tr>
        <th>
            Map Id
        </th>
        <th>
            Map Name
        </th>
        <th>
            Item
        </th>
        <th>
        </th>
    </tr>
    @{
        int i = 0;
    }
    @foreach (var map in Model.Maps)
    {
        <tr class="@(i % 2 == 1 ? "mod" : "")">
            <td>@map.MapId
            </td>
            <td>@map.DisplayName
            </td>
            <td>@(map.ItemId != 0 ? new HtmlString(String.Format("{0} - {1}", map.ItemId, ((ItemCache)ViewBag.ItemCache).GetItemName(map.ItemId))) : Html.WarningNotif(Url, "No item recommendation", "No item recommendation"))
            </td>
            <td>
                <a id="@String.Format("editMap{0}Link", @map.MapId)" href="#" onclick="LoadEditMapItem('@Url.Action("LoadEditMapItem", "Map")', '@ViewBag.ApplicationVersion', @map.MapId); return false;"
                title="Edit map">
                    <img src="@Url.Content("~/Content/img/b_edit.png")" alt="Edit recommendation" /></a>
            </td>
        </tr>
        i++;
    }
</table>
</form>

Cmune.Channels.Instrumentation/Views/Map/Partial/MapItemForm.cshtml
<form method="post" action="">
Recommend Item for the map : @Model.DisplayName
<br />
    @Html.DropDownList("RecommendedItemList", Html.GetSelectListItemView((List<int>)ViewBag.RecommendableItems, (ItemCache)ViewBag.ItemCache, (string)Model.RecommendedItemId.ToString()))
    <input type="button" value="Save" onclick="SaveMapItem('@Url.Action("SaveMapItem", "Map")', '@Url.Action("GetMapItems", "Map")', '@ViewBag.ApplicationVersion', '@Model.MapId', $('#RecommendedItemList').val())" />
</form>