Cmune.Channels.Instrumentation/Controllers/ClanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cmune.DataCenter.Common.Entities;
using Cmune.DataCenter.Business;
using UberStrike.DataCenter.Common.Entities;
using Cmune.DataCenter.DataAccess;
using UberStrike.DataCenter.Business;
using Cmune.DataCenter.Utils;
using Cmune.Channels.Instrumentation.Models.Enums;
using Cmune.Channels.Instrumentation.Utils;

namespace Cmune.Channels.Instrumentation.Controllers
{
    [Authorize(Roles = MembershipRoles.Administrator)]
    public class ClanController : BaseController
    {
        #region Properties and Parameters

        int _clansCount = 30;
        public int ClanId { get; set; }

        #endregion

        #region Constructors

        public ClanController() :base()
        {
            ViewBag.Title = ViewBag.ActiveTab = CmuneMenu.MainTabs.Clans;
        }

        #endregion

        #region Actions

        public ActionResult Index()
        {
            return RedirectToAction("Search");
        }

        public ActionResult Search()
        {
            ViewBag.Title += " | Search";

            return View();
        }

        public ActionResult See(int clanId)
        {
            ViewBag.Title += " | See";
            bool isClanLeaderNotifiable = true;

            ClanView clan = CmuneGroups.GetGroupView(clanId);

            if (clan != null)
            {
                ViewData["memberCmid"] = clan.OwnerCmid.ToString();
                ViewData["memberEmail"] = String.Empty;
                ViewData["memberName"] = String.Empty;
                ViewData["clanName"] = clan.Name;
                ViewData["clanTag"] = clan.Tag;
                ViewData["clanMotto"] = clan.Motto;
                ViewData["clanId"] = clan.GroupId;

                Member clanLeader = CmuneMember.GetMember(clan.OwnerCmid);

                if (clanLeader != null)
                {
                    if (CmuneMember.IsMemberEsnsOnly(clanLeader))
                    {
                        isClanLeaderNotifiable = false;
                    }
                    else
                    {
                        ViewData["ownerEmailHiddenField"] = clanLeader.Login;
                        ViewData["ownerNameHiddenField"] = clan.OwnerName;
                    }
                }

                ViewData["notifiable"] = isClanLeaderNotifiable;
                ViewData["clanMembers"] = clan.Members;

                ViewData["IsClanExisting"] = true;
            }
            else
            {
                ViewData["IsClanExisting"] = false;
            }

            return View();
        }

        #endregion

        #region Methods

        #region Search

        [ValidateInput(false)]
        public ActionResult GetClans(FormCollection form)
        {
            string clanName = form["ClanNameTextBox"];
            string clanTag = form["ClanTagTextBox"];
            string clanMemberName = form["ClanMemberNameTextBox"];

            List<BasicClanView> clans = CmuneGroups.GetBasicClansView(UberStrikeCommonConfig.ApplicationId, 0, _clansCount, clanName, clanTag, clanMemberName);

            return PartialView("Partial/GetClans", clans);
        }

        #endregion

        #region See

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection form)
        {
            string action = string.Empty;
            string message = string.Empty;
            bool isModified = false;
            string newValue = string.Empty;

            action = form["action"];

            ClanId = Int32.Parse(form["clanId"]);
            
            int groupOperationResult = 0;
            bool notify = false;
            string explanation = string.Empty;

            bool actionDone = false;
            switch (form["action"])
            {
                case "changeTag":
                    if (form["newClanTag"] != form["clanTag"] && !String.IsNullOrEmpty(form["newClanTag"]))
                    {
                        groupOperationResult = UberStrikeGroups.SetGroupTag(ClanId, form["newClanTag"], LocaleIdentifier.EnUS);

                        if (form["notifyForNewClanTag"] != null && form["notifyForNewClanTag"].ToString().ToLower() == "on")
                            notify = true;
                        explanation = form["explanationForNewClanTag"];
                        actionDone = true;
                    }
                    break;
                case "changeName":
                    if (form["newClanName"] != form["clanName"] && !String.IsNullOrEmpty(form["newClanName"]))
                    {
                        groupOperationResult = CmuneGroups.SetGroupName(ClanId, form["newClanName"], LocaleIdentifier.EnUS);
                        if (form["notifyForNewClanName"] != null && form["notifyForNewClanName"].ToString().ToLower() == "on")
                            notify = true;
                        explanation = form["explanationForNewClanName"];
                        actionDone = true;
                    }
                    break;
                case "changeMotto":
                    if (form["newClanMotto"] != form["clanMotto"] && !String.IsNullOrEmpty(form["newClanMotto"]))
                    {
                        groupOperationResult = CmuneGroups.SetGroupMotto(ClanId, form["newClanMotto"]);
                        if (form["notifyForNewClanMotto"] != null && form["notifyForNewClanMotto"].ToString().ToLower() == "on")
                            notify = true;
                        explanation = form["explanationForNewClanMotto"];
                        actionDone = true;
                    }
                    break;
            }

            if (actionDone == true)
            {
                CheckOperationResult.CheckGroupOperationResult(groupOperationResult, ref isModified, ref message);
                if (notify == true && groupOperationResult == GroupOperationResult.Ok)
                {
                    CmuneMail.SendEmailNotification(EmailNotificationType.ChangeClanMotto, explanation, form["memberEmail"], form["memberName"], EmailAddressStatus.Invalid);
                }
            }

            var json = new JsonResult() { Data = new { isModified = isModified, message = message, action = form["action"], newValue = newValue } };
            return json;
        }

        [HttpPost]
        public ActionResult Delete(int clanId, int cmid)
        {
            bool isModified = false;
            string message = string.Empty;

            CmuneGroups.DisbandGroup(clanId, cmid);
            isModified = true;
            message = "The clan has been disbanded, reloading the page...";

            var json = new JsonResult() { Data = new { IsModified = isModified, Message = message, ReturnUrl = ApplicationPath + "Clan/Search"} };
            return json;
        }

        [HttpPost]
        public JsonResult MakeLeader(int clandId, int oldLeaderCmid, int newLeaderCmid)
        {
            int result = CmuneGroups.TransferOwnership(clandId, oldLeaderCmid, newLeaderCmid);

            bool isOk = result == GroupOperationResult.Ok;

            JsonResult ret = new JsonResult { Data = new { IsOk = isOk } };
            return ret;
        }

        [HttpPost]
        public JsonResult KickFromClan(int clandId, int cmid)
        {
            int result = CmuneGroups.LeaveAClan(clandId, cmid);

            bool isOk = result == GroupOperationResult.Ok;

            JsonResult ret = new JsonResult { Data = new { IsOk = isOk } };
            return ret;
        }

        #endregion

        #endregion
    }
}

Cmune.Channels.Instrumentation/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Cmune.Channels.Instrumentation.Business;
using Cmune.Channels.Instrumentation.Models;
using Cmune.Channels.Instrumentation.Models.Display;
using Cmune.Channels.Instrumentation.Models.Enums;
using Cmune.Channels.Instrumentation.Utils;
using Cmune.DataCenter.Business;
using Cmune.DataCenter.Common.Entities;
using Cmune.DataCenter.Common.Utils;
using Cmune.DataCenter.DataAccess;
using Cmune.DataCenter.Utils;
using Cmune.Instrumentation.Business;
using UberStrike.DataCenter.Business;
using UberStrike.DataCenter.Business.Views;
using UberStrike.DataCenter.Common.Entities;
using UberStrike.DataCenter.DataAccess;
using UberStrike.DataCenter.Utils;
using PPUsers = UberStrike.DataCenter.Business.Users;
using Cmune.Channels.Instrumentation.Extensions;
using UberStrike.Core.Types;

namespace Cmune.Channels.Instrumentation.Controllers
{
    [Authorize(Roles = MembershipRoles.Administrator)]
    public class MemberController : BaseController
    {
        #region Properties

        private int _applicationId = 1;
        private int _cmid = 0;

        public int ApplicationId
        {
            get { return _applicationId; }
            private set { _applicationId = value; }
        }

        public int Cmid
        {
            get { return _cmid; }
            private set { _cmid = value; }
        }

        #region (for create test account)

        const string TestAccountNameTemplate = "Test Account ";
        const string TestAccountEmailTemplate = "testaccount@@@INDEXER@@@@yopmail.com";
        static readonly List<int> DefaultGears = new List<int> { 1090, 1089, 1088, 1087, 1086, 1085, 1084 };
        static readonly List<int> DefaultWeapons = new List<int> { 1007, 1006, 1005, 1004, 1003, 1002, 1001, 1000 };
        const int DefaultCredits = 1000000;
        const int DefaultPoints = 1000000;
        const int DefaultLevel = 20;
        static readonly LoadoutView DefaultLoadout = new LoadoutView(0, 0, 1089, 0, 1085, 0, 0, 0, 1086, 1084, 1088, 1000, 0, 0, 0, AvatarType.LutzRavinoff, 1087, 1001, 0, 0, 0, 1002, 0, 0, 0, 0, 0, 0, 0, 0, "c69c6d");

        #endregion

        #endregion

        public MemberController()
            : base()
        {
            ViewBag.Title = ViewBag.ActiveTab = CmuneMenu.MainTabs.Members;
            ViewBag.PublishVersion = ConfigurationUtilities.ReadConfigurationManager("PublishVersion");

            UseProdDataContext();
        }

        #region Actions

        public ActionResult Index()
        {
            return RedirectToAction("Search");
        }

        public ActionResult ManageMemberAccess()
        {
            ViewBag.SubActiveTab = CmuneMenu.MemberSubTabs.ManageMemberAccess;
            ViewBag.Title += String.Format(" | {0}", CmuneMenu.MemberSubTabs.ManageMemberAccess);

            List<MemberAccess> membersAccess = CmuneMember.GetNonDefaultMemberAccess(CommonConfig.ApplicationIdUberstrike);
            List<int> cmids = membersAccess.Select(mA => mA.Cmid).ToList();
            Dictionary<int, string> names = CmuneMember.GetMembersNames(cmids);
            List<MemberAccessDisplay> accessLevelsDisplay = new List<MemberAccessDisplay>();

            foreach (MemberAccess memberAccess in membersAccess)
            {
                MemberAccessDisplay accessLevelDisplay = new MemberAccessDisplay(memberAccess.Cmid, names[memberAccess.Cmid], (MemberAccessLevel)memberAccess.AccessLevel);
                accessLevelsDisplay.Add(accessLevelDisplay);
            }

            ViewData["memberAccessLevelsDisplay"] = accessLevelsDisplay;

            List<SelectListItem> accessLevelList = new List<SelectListItem>();
            foreach (var item in AdminCache.GenerateMemberAccessLevelDropDownListItems())
                accessLevelList.Add(new SelectListItem() { Text = item.Text, Value = item.Value });
            ViewData["accessLevelList"] = accessLevelList;
            return View();
        }

        public ActionResult Search()
        {
            ViewBag.SubActiveTab = CmuneMenu.MemberSubTabs.Search;
            ViewBag.Title += String.Format(" | {0}", CmuneMenu.MemberSubTabs.Search);

            ViewData["esnsType"] = AdminCache.GenerateEsnsDropDownListItems();

            return View();
        }

        public ActionResult See(string cmid)
        {
            Stopwatch watch = Stopwatch.StartNew();
            long seeStart = watch.ElapsedMilliseconds;
            long getNameStart = 0;
            long getNameEnd = 0;
            long getIsMemberEsnsOnlyStart = 0;
            long getIsMemberEsnsOnlyEnd = 0;
            long getMemberAccessStart = 0;
            long getMemberAccessEnd = 0;
            long getCreditStart = 0;
            long getCreditEnd = 0;
            long getEsnsStart = 0;
            long getEsnsEnd = 0;
            long getRankingStart = 0;
            long getRankingEnd = 0;
            long getGroupStart = 0;
            long getGroupEnd = 0;
            long getGroupMemberStart = 0;
            long getGroupMemberEnd = 0;
            long getPreviousEmailsStart = 0;
            long getPreviousEmailsEnd = 0;
            long getNotesStart = 0;
            long getNotesEnd = 0;

            ViewBag.SubActiveTab = CmuneMenu.MemberSubTabs.See;
            ViewBag.Title += String.Format(" | {0}", CmuneMenu.MemberSubTabs.See);
            ApplicationId = 1;

            bool isCmidParsed = false;
            bool isMemberExisting = false;

            isCmidParsed = Int32.TryParse(cmid, out _cmid);

            Member member = null;
            ID3 id3 = null;

            if (isCmidParsed)
            {
                member = CmuneMember.GetMember(this.Cmid);

                getNameStart = watch.ElapsedMilliseconds;

                id3 = CmuneMember.GetId3(this.Cmid);

                getNameEnd = watch.ElapsedMilliseconds;

                isMemberExisting = member != null && id3 != null;
            }

            if (isMemberExisting)
            {
                MemberOriginDisplay memberOrigin = UserActivityBusiness.GetMemberOrigin(this.Cmid);
                ViewData["MemberOrigin"] = memberOrigin;

                getIsMemberEsnsOnlyStart = watch.ElapsedMilliseconds;

                bool isMemberEsnsOnly = CmuneMember.IsMemberEsnsOnly(member);

                getIsMemberEsnsOnlyEnd = watch.ElapsedMilliseconds;

                #region Basic information

                ViewData["memberCmid"] = this.Cmid;
                ViewData["memberName"] = id3.Name;
                ViewBag.EmailAddressState = member.EmailAddressState;
                ViewData["memberEmail"] = member.Login;
                ViewData["isEmailPasswordVisible"] = ViewData["isUsernameExplainationVisible"] = ViewData["isUsernameCheckBoxVisible"] = true;

                if (isMemberEsnsOnly == true) // means only sign up in social network
                {
                    ViewData["isEmailPasswordVisible"] = false;
                    ViewData["isUsernameExplainationVisible"] = false;
                    ViewData["isUsernameCheckBoxVisible"] = false;
                    ViewData["isCompleteUserLinkButtonVisibile"] = true;
                }

                getMemberAccessStart = watch.ElapsedMilliseconds;

                MemberAccess memberAccess = CmuneMember.GetMemberAccess(this.Cmid, ApplicationId);

                getMemberAccessEnd = watch.ElapsedMilliseconds;

                ViewData["memberAccessIsAccountDisabled"] = memberAccess.IsAccountDisabled;
                ViewData["memberAccessIsAccoundDisabledBanStatus"] = GetBanStatusText((BanMode)memberAccess.IsAccountDisabled, memberAccess.AccountDisabledUntil);
                ViewData["memberAccessIsChatDisabled"] = memberAccess.IsChatDisabled;
                ViewData["memberAccessIsChatDisabledBanStatus"] = GetBanStatusText((BanMode)memberAccess.IsChatDisabled, memberAccess.ChatDisabledUntil);

                ViewBag.AccountCreationDate = member.ResLastSyncDate;
                ViewBag.LastLoginDate = member.LastAliveAck ?? DateTime.MinValue;

                List<SelectListItem> MemberAccessDropDownList = new List<SelectListItem>();

                foreach (var item in AdminCache.GenerateMemberAccessLevelDropDownListItems())
                {
                    MemberAccessDropDownList.Add(new SelectListItem() { Text = item.Text, Value = item.Value, Selected = (item.Value == memberAccess.AccessLevel.ToString()) });
                }

                ViewData["MemberAccessDropDownList"] = MemberAccessDropDownList;

                getCreditStart = watch.ElapsedMilliseconds;

                Credit memberToCharge = CmuneEconomy.GetCreditByMemberID(this.Cmid);

                getCreditEnd = watch.ElapsedMilliseconds;

                ViewData["memberCredits"] = (memberToCharge.NbCredits ?? 0).ToString();
                ViewData["memberPoints"] = (memberToCharge.NbPoints ?? 0).ToString();

                #endregion

                #region Esns handles

                getEsnsStart = watch.ElapsedMilliseconds;

                List<ESNSIdentity> esnsIdentityMember = CmuneMember.GetMemberEsns(this.Cmid);

                getEsnsEnd = watch.ElapsedMilliseconds;

                List<EsnsHandleDisplay> esnsIdentitiesDisplay = esnsIdentityMember.ConvertAll<EsnsHandleDisplay>(new Converter<ESNSIdentity, EsnsHandleDisplay>(eH => new EsnsHandleDisplay((EsnsType)eH.Type, eH.Handle)));
                ViewData["esnsIdentitiesDisplay"] = esnsIdentitiesDisplay;

                #endregion

                #region Stats history

                getRankingStart = watch.ElapsedMilliseconds;

                GetRanking(this.Cmid);

                getRankingEnd = watch.ElapsedMilliseconds;

                #endregion

                #region Clan

                getGroupStart = watch.ElapsedMilliseconds;

Cmune.Channels.Instrumentation/Views/Member/Partial/BannedIps.cshtml
@model List<BannedIpView>

<table class="currentInventory searchResultTable" style="width: 99%; margin: 0 0 25px 0;">
    <tr>
        <th>
            IP
        </th>
        <th>
            Network address
        </th>
        <th>
            Banning time
        </th>
        <th>
            Banned until
        </th>
        <th>
            By
        </th>
        <th>
            Targeting
        </th>
        <th>
            Reason
        </th>
        <th>
        </th>
        <th>
        </th>
    </tr>
    @if (Model != null && Model.Count > 0)
        {
            int i = 0;
            foreach (var bannedIp in Model)
            {
    <tr class="@(i % 2 == 1 ? "mod":"")">
        <td>
            @TextUtilities.InetNToA(bannedIp.IpAddress)
        </td>
        <td>
            @bannedIp.IpAddress
        </td>
        <td>
            @bannedIp.BanningDate.ToNiceDisplay()
        </td>
        <td>
            @(bannedIp.BannedUntil.HasValue ? bannedIp.BannedUntil.Value.ToString("dd MMM yy HH:mm:ss") : "Permanent")
        </td>
        <td>
            @bannedIp.SourceName
        </td>
        <td>
            <a href='@Url.Action("See", "Member")?cmid=@bannedIp.TargetCmid' target="_blank">
                @bannedIp.TargetName</a>
        </td>
        <td>
            @bannedIp.Reason
        </td>
        <td>
            <a id="modifyIpBan@(bannedIp.IpAddress)" href="#" onclick="displayBanIpPopUp('@TextUtilities.InetNToA(bannedIp.IpAddress)', @bannedIp.TargetCmid, 'modifyIpBan@(bannedIp.IpAddress)', 'modify', function() { loadBannedIps() }); return false;">
                <img src="@Url.Content("~/Content/img/b_edit.png")" alt="Edit IP ban" /></a>
        </td>
        <td>
            <a id="unbanIp@(bannedIp.IpAddress)" href="#" onclick="displayBanIpPopUp('@TextUtilities.InetNToA(bannedIp.IpAddress)', @bannedIp.TargetCmid, 'unbanIp@(bannedIp.IpAddress)', 'unban', function() { loadBannedIps() }); return false;">
                <img src="@Url.Content("~/Content/img/b_drop.png")" alt="Unban ban" /></a>
        </td>
    </tr>
              i++;
            }
    }
</table>
@Html.GeneratePagination((PaginationModel)ViewBag.PaginationModel, "loadBannedIps();")
@if (Model == null || (Model != null && Model.Count == 0))
    {
<p class="bold">
    There is no banned Ip matching with your query</p>
}

Cmune.Channels.Instrumentation/Views/Member/Partial/Clan.cshtml
@model ClanMemberDisplay
<div style="margin-top:20px;">
    <h3 style="margin-bottom:20px;">
        Clan</h3>
    @if (Model != null)
    {
        <span>This member is @Model.Position.ToString() of <a href="@Url.Action("See", "Clan")?ClanId=@Model.ClanId">[@Model.ClanTag] @Model.ClanName</a>
            since @Model.MemberSince.ToNiceDisplay(true)</span>
    }
    else
    {
        <span>This member is not part of any clan.</span>
    }
</div>

Cmune.Channels.Instrumentation/Views/Member/Partial/Contacts.cshtml
@model List<ContactDisplay>

<div id="friendsArea">
    <p style="text-align:left; margin-bottom:15px;">
        <span class="bold">@(((PaginationModel)ViewBag.ContactsPaginationModel).TotalCount)</span> contacts
    </p>
    <div class="clear">
    </div>
    @if (Model.Count > 0)
    {
        foreach (var contact in Model)
        {
    <div class="left" style="margin:5px; padding:5px; width:230px; height:140px;">
        <div class="left" style="width:53px;">
            <img src="@Url.Content("~/Content/img/suricat.jpg")" style="width:53px;" alt="Suricat" />
        </div>
        <div class="left" style="font-weight:bold; height:36px; padding-left:15px; width:160px;">
            <a href="@Url.Action("See", "Member")?cmid=@contact.Cmid" target="_blank">@contact.Name</a>
        </div>
        <table class="statisticTable left" style="width:100%">
            <tr>
                <th>
                    @Html.Label("Ranking")
                </th>
                <td>
                    @Html.Label(contact.Ranking.ToString())
                </td>
            </tr>
            <tr>
                <th>
                    @Html.Label("Kills")
                </th>
                <td>
                    @Html.Label(contact.Kills.ToString())
                </td>
            </tr>
        </table>
    </div>
        }
    <div class="clear">
    </div>
    }
    @Html.GeneratePagination((PaginationModel)ViewBag.ContactsPaginationModel, "getContacts();")
</div>

Cmune.Channels.Instrumentation/Views/Member/Partial/DailyStatistics.cshtml
@model List<StatsHistoryDisplay>

<div>
    @if (Model.Count > 0)
    {
        DateTime now = DateTime.Now;
        int i = 0;
    <table class="searchResultTable">
        <tr>
            <th></th>
            <th>Kills</th>
            <th>Deaths</th>
            <th>Kdr</th>
            <th>Accuracy</th>
        </tr>
        @foreach (var item in Model)
        {
            now = now.AddDays(-1);
        <tr>
            <td>@now.ToString("ddd MM/dd")</td>
            <td>@item.Kills</td>
            <td>@item.Deaths</td>
            <td>@item.Kdr.ToString("F2")</td>
            <td>@item.Precision.ToString("P2")</td>
        </tr>
        }
    </table>         
    }
    else
    {
    <p>There is not yet stats history for this member.</p>
    }

    <!--
        @ViewBag.ElapsedMilliseconds
    -->

</div>

Cmune.Channels.Instrumentation/Views/Member/Partial/IpsAndOtherAccounts.cshtml
@model List<LastIpView>
<script type="text/javascript">
    var ipBanTargetCmid = 0;
    var ipBanIpAddressToBan = '';
</script>
<div id="IPsAccountsDiv" style="margin: 25px 0 0 0;">
    <p style="margin-bottom: 15px;">
        Only data for the last 30 days is displayed</p>
    @{Dictionary<int, string> accountNames = new Dictionary<int, string>();}
    @if (Model.Count > 0)
    {
        int i = 0;
        <table class="searchResultTable">
            <tr>
                <th>
                    IP
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                    Last login
                </th>
            </tr>
            @foreach (var linkedIp in Model)
            {
                <tr class="@(i % 2 == 1 ? "mod" : "")">
                    <td>
                        <a href="#" onclick="$('#linkedMembers' + @linkedIp.Ip).toggle(); return false;">@TextUtilities.InetNToA(linkedIp.Ip)</a>
                        (@linkedIp.Ip)
                    </td>
                    <td>
                        @if (linkedIp.BannedIpView != null)
                        {
                            @:Banned until @(linkedIp.BannedIpView.BannedUntil != null ? String.Format("{0} ({1} days)", linkedIp.BannedIpView.BannedUntil.Value.ToString("MM/dd"), Math.Ceiling(linkedIp.BannedIpView.BannedUntil.Value.Subtract(DateTime.Now).TotalDays)) : "the end of time")
                                                                        }
                    </td>
                    <td>
                        <a id="banIp@(linkedIp.Ip)Link" href="#" onclick="displayBanIpPopUp('@TextUtilities.InetNToA(linkedIp.Ip)', $('#memberCmid').val(), 'banIp@(linkedIp.Ip)Link', '@(linkedIp.BannedIpView != null ? "modify" : "ban")', function() { loadIpsAndOtherAccounts(); getMemberNotes(); }); return false;">@(linkedIp.BannedIpView != null ? "Modify ban" : "Ban IP")</a>
                    </td>
                    <td>
                        @linkedIp.LastConnectionDate.ToNiceDisplay(true)
                    </td>
                </tr>
                <tr id="linkedMembers@(linkedIp.Ip)" style="display:none;@(i % 2 == 1 ? "background-color:#DCDCDC" : "")">
                    <td colspan="4" style="padding-left: 50px;">
                        @foreach (var linkedMember in linkedIp.LinkedMembers)
                        {
                            if (!accountNames.ContainsKey(linkedMember.Cmid))
                            {
                                accountNames.Add(linkedMember.Cmid, linkedMember.Name);
                            }
                            <a href='@Url.Action("See", "Member")?cmid=@linkedMember.Cmid' target="_blank">@linkedMember.Name</a><br />
                        }
                    </td>
                </tr>
                        i++;
            }
        </table>
    }
    else
    {
        <p>
            There is no IP linked to this account.</p>
    }
    <span style="display: block; margin: 15px 0 15px 0;">Possibly linked to @accountNames.Keys.Count
        accounts:</span>
    @if (accountNames.Keys.Count > 0)
    {
        <table>
            <tr>
                <td>
                    Account
                </td>
            </tr>
            @{int i = 0;}
            @foreach (var item in accountNames)
            {
                <tr>
                    <td>
                        <a href='@Url.Action("See", "Member")?cmid=@item.Key' target="_blank">
                            @item.Value</a>
                    </td>
                </tr>
            }
        </table>
    }
</div>

Cmune.Channels.Instrumentation/Views/Member/Partial/PreviousAccountsByName.cshtml
@model List<AccountPreviousNameDisplay>

@if (Model.Count > 0)
{
    int i = 0;
    <table class="searchResultTable">
        <tr>
            <th>Linked to account</th>
            <th>Until</th>
            <th>Modified from</th>
        </tr>
        @foreach (var account in Model)
        {
        <tr class="@(i % 2 == 1 ? "mod" : "")">
            <td><a href="@Url.Action("See", "Member")?cmid=@account.Cmid" target="_blank">@account.AccountName</a></td>
            <td>@account.ChangeDate.ToString("MM/dd/yy HH:mm:ss")</td>
            <td>@account.Ip</td>
        </tr>
            i++;
        }
    </table>
}
else
{
    <p>Either this user name is still linked to an account or it was never user before.</p>
}

Cmune.Channels.Instrumentation/Views/Member/Partial/SearchUsers.cshtml
@{var usersListToSend = (List<UserV>)ViewData["usersListToSend"];}
@if (usersListToSend.Count > 0)
{
    <div>
        <table class="searchResultTable">
            <tr>
                <th>
                </th>
                <th>
                    Login
                </th>
                <th>
                    Name
                </th>
                <th>
                    Last login
                </th>
            </tr>
            @{int i = 0;}
            @foreach (var user in usersListToSend)
            { 
                <tr class="@(i % 2 == 1 ? "mod" : "")">
                    <td>
                        <a href="@Url.Action("See", "Member")?cmid=@user.UserID.ToString()">Profile</a>
                    </td>
                    <td>
                        @user.Login
                    </td>
                    <td>
                        @user.Name
                    </td>
                    <td>
                        @user.LastAliveAck.ToNiceDisplay()
                    </td>
                </tr>
                i++;
            }
        </table>
        @Html.GeneratePagination((PaginationModel)ViewBag.PaginationModel, "searchUsers()")
    </div>
}