UberStrike.Channels.Facebook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Facebook.Web.Mvc;
using Facebook;
using Facebook.Web;
using System.Configuration;
using System.Collections.Specialized;
using UberStrike.Channels.Facebook.Models;
using UberStrike.DataCenter.DataAccess;
using UberStrike.DataCenter.Business;
using Cmune.DataCenter.DataAccess;
using Cmune.DataCenter.Common.Entities;
using UberStrike.Channels.Facebook.Utils;
using Cmune.DataCenter.Business;
using UberStrike.DataCenter.Common.Entities;
using Cmune.DataCenter.Utils;
using System.Text;
using System.Globalization;
using UberStrike.Channels.Utils;

namespace UberStrike.Channels.Facebook.Controllers
{
    [CanvasAuthorize(Permissions = "publish_stream,email,publish_actions")]
    public class HomeController : BaseController
    {
        #region Properties and Parameters

       

        #endregion

        #region Constructors

        public HomeController() : base()
        {
           
        }

        #endregion

        public ActionResult RefreshMenu()
        {
            return PartialView("_Menu", FbUserModel);
        }

        public ActionResult Index()
        {
            if (FbUserModel.FacebookId <= 0)
            {
                throw new ArgumentOutOfRangeException("FacebookId can't be 0");
            }

            PrepareGame(base.CmuneCookie);
            /**** end ****/

            return View("Play", FbUserModel);
        }

        void PrepareGame(CmuneCookie cmuneCookie)
        {
            string developerId = CmuneEconomy.PaymentWriteDeveloperId(UberStrikeCommonConfig.ApplicationId, ChannelType.WebFacebook, 0);

            int unityBuildTypeIndex = ConfigurationUtilities.ReadConfigurationManagerInt("UnityBuild");
            string cultureName = ConfigurationUtilities.ReadConfigurationManager("UnityDefaultCulture");

            if (!Request.QueryString["lang"].IsNullOrFullyEmpty())
            {
                cultureName = Request.QueryString["lang"];
            }

            string initialUnityArguments = UnityArgsBuilder.BuildInitialUnityArguments(ChannelType.WebFacebook, cultureName);
            StringBuilder gameUrlArguments = new StringBuilder();

            // If the cookie belongs to the currentUser
            if (cmuneCookie != null && FbUserModel.IsAuthenticated)
            {
                gameUrlArguments.Append("&cmid=");
                gameUrlArguments.Append(cmuneCookie.Cmid.ToString());
                gameUrlArguments.Append("&time=");
                gameUrlArguments.Append(Uri.EscapeDataString(cmuneCookie.ExpirationTime.ToString("G", CultureInfo.CreateSpecificCulture(cultureName)).Base64Encode()));
                gameUrlArguments.Append("&content=");
                gameUrlArguments.Append(Uri.EscapeDataString(cmuneCookie.CookieEncryptedContent));
                gameUrlArguments.Append("&hash=");
                gameUrlArguments.Append(Uri.EscapeDataString(cmuneCookie.CookieHash));
                gameUrlArguments.Append("&esnsMemberId=");
                gameUrlArguments.Append(FbUserModel.FacebookId);
            }
            else
            {
                gameUrlArguments.Append("&loginmode=facebookrego&esnsMemberId=");
                gameUrlArguments.Append(FbUserModel.FacebookId.ToString());
            }

            ViewBag.DeveloperId = developerId;
            ViewBag.UnityArguments = initialUnityArguments + gameUrlArguments.ToString();
        }

        public ActionResult About()
        {

            return View();
        }
    }
}

UberStrike.Channels.Facebook/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Facebook.Web.Mvc;
using System.Configuration;
using Cmune.DataCenter.Business;
using Cmune.DataCenter.DataAccess;
using Cmune.DataCenter.Utils;
using Cmune.DataCenter.Common.Entities;
using UberStrike.DataCenter.Common.Entities;
using UberStrike.Channels.Utils;

namespace UberStrike.Channels.Facebook.Controllers
{
    [CanvasAuthorize(Permissions = "publish_stream,email,publish_actions")]
    public class OfferController : BaseController
    {
        #region Properties and Parameters

        /// <summary>
        /// Hash used to identify the internal application Id and the channel
        /// </summary>
        public string DeveloperId = String.Empty;
        /// <summary>
        /// Hash to ensure that our custom fields are not modified
        /// </summary>
        public string Hash = String.Empty;
        /// <summary>
        /// Name of the member loading this page
        /// </summary>
        public string Name = String.Empty;
        /// <summary>
        /// Super Rewards application Id as we have to use a different iframe depending on the channel
        /// </summary>
        public string SuperRewardsApplicationId = String.Empty;

        bool displayError;
        /// <summary>
        /// Cmid
        /// </summary>
        public int Cmid = 0;

        #endregion

        #region Constructors

        public OfferController()
            : base()
        {
            base.CurrentTab = Utils.Menu.MainTab.Credit;
        }

        #endregion

        private void InitIframeValues()
        {
            displayError = true;
            if (FbUserModel.IsAuthenticated)
            {
                ID3 memberId3 = CmuneMember.GetId3(FbUserModel.Cmid);

                if (memberId3 != null)
                {
                    bool isInCommon = ConfigurationUtilities.ReadConfigurationManagerBool("IsSuperRewardsInCommon");

                    if (isInCommon)
                    {
                        this.SuperRewardsApplicationId = UnityArgsBuilder.GetSuperRewardsApplicationId(ChannelType.WebFacebook);
                    }
                    else
                    {
                        this.SuperRewardsApplicationId = ConfigurationUtilities.ReadConfigurationManager("SuperRewardsApplication");
                    }

                    ViewBag.SuperRewardsApplicationId = SuperRewardsApplicationId;
                    ViewBag.Name = HttpUtility.HtmlEncode(memberId3.Name);
                    ViewBag.FacebookThirdPartyId = FbUserModel.FacebookThirdPartyId;
                    ViewBag.Cmid = FbUserModel.Cmid;
                    ViewBag.DeveloperId = DeveloperId = CmuneEconomy.PaymentWriteDeveloperId(UberStrikeCommonConfig.ApplicationId, ChannelType.WebFacebook, 0);
                    ViewBag.Hash = CmuneEconomy.SuperRewardsGenerateCmuneHash(FbUserModel.FacebookThirdPartyId.ToString(), DeveloperId, FbUserModel.Cmid);
                    displayError = false;
                }
            }
        }

        public ActionResult Index()
        {
            InitIframeValues();
            
            ViewBag.HasError = displayError;
            if (Request.IsAjaxRequest())
                return PartialView();
            return View();
        }


        public ActionResult FacebookCredits()
        {
            ViewBag.Cmid = FbUserModel.Cmid;
            ViewBag.HasError = false;
            if (Request.IsAjaxRequest())
                return PartialView(FbUserModel);
            return View(FbUserModel);
        }

        public ActionResult Bundle()
        {
            ViewBag.Cmid = FbUserModel.Cmid;
            ViewBag.HasError = false;
            return PartialView(FbUserModel);
        }

        public ActionResult EarnFacebookCredits()
        {
            ViewBag.Cmid = FbUserModel.Cmid;
            ViewBag.HasError = false;
            if (Request.IsAjaxRequest())
                return PartialView(FbUserModel);
            return View(FbUserModel);
        }

        public ActionResult RedeemEpin()
        {
            ViewBag.UberStrikePortal = ConfigurationUtilities.ReadConfigurationManager("UberStrikePortal");
            ViewBag.UberStrikePortalEpinPage = ConfigurationUtilities.ReadConfigurationManager("UberStrikePortalEpinPage");
            return PartialView(FbUserModel);
        }
    }
}

UberStrike.Channels.Facebook/Views/Home/Play.cshtml
@model UberStrike.Channels.Utils.Models.FacebookUserModel
@{
    ViewBag.Title = "Home Page";
}
@section HeaderJavascript{
    <script type="text/javascript">
        var developerId = '@ViewBag.DeveloperId';
        var unityArgs = '@Html.Raw(ViewBag.UnityArguments)';
        var cmid = '@Model.Cmid';
    </script>
    <script type="text/javascript">
        var webServicesBaseURL = '@ConfigurationManager.AppSettings["InstrumentationWsBaseUrl"]';
        var superRewardsIframeUrl = '@Url.Action("Iframe", "Offer")';
        var cookieDomainName = '@ConfigurationManager.AppSettings["CookieDomainName"]';
    </script>
    @{
        var PublishVersion = ConfigurationManager.AppSettings["PublishVersion"];
    }
    <script type="text/javascript">
        Shadowbox.init({
            displayNav: true,
            modal: true,
            enableKeys: false,
            animate: false,
            animateFade: false
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            StartServerClock();
            UnityEvent.OnLoadSuccess = function () {
                DisplayBanner();
                $(window).resize(function () { ResizeUnity(); });
            }
            UnityEvent.OnLoadFailure = function () {
                DisplayBanner();
            }
            //760, 560
            EmbedUnity(unityArgs, GetUnityWidth(), GetUnityHeight(), webChannel);
            //EmbedUnity(unityArgs,  760, 560, webChannel);
        });
    </script>
}
<div id="messageDiv" style="display: none; position: relative; top: 0px; left: 0px;">
    <div style="position: absolute; width: 100%; padding-top: 50px; margin: auto; text-align: center;">
        <p>
            <span id="messageContentSpan"></span>
        </p>
        <p style="color: #9F9F9F; margin-bottom: 40px">
            <span id="messageUrlSpan"></span>
        </p>
        <p>
            <a id="messageLinkA" href="" onclick="" class="silver">Open this link in another tab</a>
            <a href="" onclick="hideMessage();return false;" class="darkGray">Go back to Game</a>
        </p>
    </div>
</div>
<div>
    <div id="unityPlayer">
    </div>
    <div id="playSpanDiv">
    </div>
    <!-- PlaySpan payment div -->
    <div id="div_b" style="display: none; padding: 10px; display: block; position: absolute; top: 150px; left: 50%; margin-left: -385px;">
    </div>
</div>
@if (ViewBag.IsFriendsCarouselEnable)
{
    <div id="SocialCarouselContainer">
        <div id="SocialCarousel" class="social_carousel">
            <img src="@Url.Image("loader.gif")" alt="loading..." />
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                type: 'POST',
                url: '@Url.Content("~/Friend/LoadUsingAppFriends")',
                data: { signed_request: '@ViewBag.SignedRequest' },
                success: function (data) {
                    $('#SocialCarousel').html(data);
                }
            });
        });
    </script>
}